networks:
  taskify_network:
    driver: bridge
    name: taskify_network
    external: false

services:
  postgres:
    image: postgres:latest
    container_name: taskify_postgres
    environment:
      POSTGRES_USER: taskify
      POSTGRES_PASSWORD: taskify
      POSTGRES_DB: taskify_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - taskify_network
  adminer:
    image: adminer:latest
    container_name: taskify_adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: taskify_postgres
      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DEFAULT_DB_NAME: taskify_db
      ADMINER_DEFAULT_USERNAME: taskify
      ADMINER_DEFAULT_PASSWORD: taskify
    depends_on:
      - postgres
    networks:
      - taskify_network
  migrate-up:
    image: migrate/migrate:latest
    profiles:
      - migration
    command: 
      [
        "-path", 
        "/sql",
        "-database", 
        "postgres://taskify:taskify@taskify_postgres:5432/taskify_db?sslmode=disable", 
        "up",
      ]
    depends_on:
      - postgres
    volumes:
      - ./migrations/sql:/sql
    networks:
      - taskify_network
  migrate-down:
    image: migrate/migrate:latest
    profiles:
      - migration
    command: 
      [
        "-path", 
        "/sql",
        "-database", 
        "postgres://taskify:taskify@taskify_postgres:5432/taskify_db?sslmode=disable", 
        "down",
      ]
    depends_on:
      - postgres
    volumes:
      - ./migrations/sql:/sql
    networks:
      - taskify_network

volumes:
  postgres_data:
    driver: local